'use strict';

const fs = require('fs');
const path = require('path');

const sourceFiles = {
  '/index.html': ['index.html', 'text/html; charset=utf-8'],
  '/quiz.html': ['quiz.html', 'text/html; charset=utf-8'],
  '/questions.js': ['questions.js', 'application/javascript; charset=utf-8'],
  '/config.js': ['config.js', 'application/javascript; charset=utf-8'],
  '/auth.js': ['auth.js', 'application/javascript; charset=utf-8'],
  '/tracker.js': ['tracker.js', 'application/javascript; charset=utf-8'],
  '/1samuel-test.html': ['1samuel-test.html', 'text/html; charset=utf-8'],
  '/test-tracker.js': ['test-tracker.js', 'application/javascript; charset=utf-8'],
  '/manifest.webmanifest': ['manifest.webmanifest', 'application/manifest+json; charset=utf-8'],
  '/service-worker.js': ['service-worker.js', 'application/javascript; charset=utf-8'],
  '/icon-192.png': ['icon-192.png', 'image/png'],
  '/icon-512.png': ['icon-512.png', 'image/png'],
};

// All Samuel quiz data files are bundled automatically — no per-file maintenance needed.
for (const file of fs.readdirSync(path.join(__dirname, 'data'))) {
  if (/^(1samuel|2samuel).*\.js$/.test(file)) {
    sourceFiles[`/data/${file}`] = [`data/${file}`, 'application/javascript; charset=utf-8'];
  }
}

const assets = Object.fromEntries(Object.entries(sourceFiles).map(([url, [file, contentType]]) => {
  const binary = contentType.startsWith('image/');
  return [url, {
    body: fs.readFileSync(path.join(__dirname, file), binary ? 'base64' : 'utf8'),
    contentType,
    encoding: binary ? 'base64' : 'text',
  }];
}));

// Doar fișierele de mai sus ajung în bundle, deci supabase/ (baremele complete)
// nu poate fi servit de Worker. Antetele repetă politica din <meta> și adaugă
// ce nu se poate exprima în pagină (frame-ancestors, nosniff).
const SUPABASE_ORIGIN = /SUPABASE_URL\s*=\s*["']([^"']+)/.exec(fs.readFileSync(path.join(__dirname, 'config.js'), 'utf8'))?.[1];
if (!SUPABASE_ORIGIN) throw new Error('Could not read SUPABASE_URL from config.js.');

const SECURITY_HEADERS = {
  'content-security-policy': [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    `connect-src 'self' ${SUPABASE_ORIGIN}`,
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join('; '),
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'no-referrer',
  'cross-origin-opener-policy': 'same-origin',
  'permissions-policy': 'geolocation=(), microphone=(), camera=(), interest-cohort=()',
};

const worker = `// Generated by build-site.js — do not edit directly.\nconst ASSETS = ${JSON.stringify(assets)};\nconst SECURITY_HEADERS = ${JSON.stringify(SECURITY_HEADERS)};\n\nexport default {\n  async fetch(request) {\n    const url = new URL(request.url);\n    const asset = ASSETS[url.pathname === '/' ? '/index.html' : url.pathname];\n    if (!asset) return new Response('Not found', { status: 404, headers: SECURITY_HEADERS });\n    const body = asset.encoding === 'base64' ? Uint8Array.from(atob(asset.body), c => c.charCodeAt(0)) : asset.body;\n    return new Response(body, { headers: { ...SECURITY_HEADERS, 'content-type': asset.contentType, 'cache-control': 'no-store' } });\n  },\n};\n`;

const output = path.join(__dirname, 'dist', 'server');
fs.mkdirSync(output, { recursive: true });
fs.writeFileSync(path.join(output, 'index.js'), worker, 'utf8');
fs.writeFileSync(path.join(output, 'package.json'), '{"type":"module"}\n', 'utf8');
console.log('Built Cloudflare Worker bundle.');
